version: '3.9'
services:
  nginx_amt:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app_amt_wiki

  app_amt_wiki:
    build:
      dockerfile: ./Dockerfile
      context: .

    ports:
    - "5005:5005"

