version: '3.9'
services:
  nginx_amt_wiki_ver2:
    image: nginx:1.23-alpine
    container_name: nginx_education
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

      - "./ssl/certbot/conf:/etc/letsencrypt"
      - "./ssl/certbot/www:/var/www/certbot"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
      - app_amt_wiki_ver3



  app_amt_wiki_ver3:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: amt_wiki_ver3
    env_file:
      - ".env"
    volumes:
      - "/home/amt_user/amt_wiki/data:/app/data"
      - "/home/amt_user/amt_wiki/data/migrations:/app/migrations"
    ports:
    - "5006:5006"

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - "./ssl/certbot/conf:/etc/letsencrypt"
      - "./ssl/certbot/www:/var/www/certbot"

