"""empty message

Revision ID: 33c98517625c
Revises: d061a6c58451
Create Date: 2024-04-07 10:46:42.513729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c98517625c'
down_revision = 'd061a6c58451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_urls',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_urls')
    # ### end Alembic commands ###
