"""empty message

Revision ID: 649936dbdba5
Revises: 739c08d86baf
Create Date: 2023-09-03 18:26:53.791968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649936dbdba5'
down_revision = '739c08d86baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
