"""empty message

Revision ID: 739c08d86baf
Revises: 
Create Date: 2023-09-03 18:13:12.711730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739c08d86baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=80), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=80), server_default='', nullable=False),
    sa.Column('login', sa.String(length=80), server_default='', nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.Column('email', sa.String(length=255), server_default='', nullable=False),
    sa.Column('role', sa.String(length=200), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
