"""empty message

Revision ID: d061a6c58451
Revises: 
Create Date: 2024-03-24 19:10:05.237295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd061a6c58451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creater_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['creater_id'], ['_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creater_id')

    # ### end Alembic commands ###
