upstream app_amt_wiki_ver3 {
  server app_amt_wiki_ver3:5006;
  }

server {
  listen 80;
  server_name amt-control.ru www.amt-control.ru;
  access_log /var/log/nginx/education.access.log;
  include  /etc/nginx/mime.types;
  location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

  return 301 https://$host$request_uri;
  }



server {
    listen 443 ssl;
    server_name amt-control.ru www.amt-control.ru;

    include /etc/nginx/mime.types;

    ssl_certificate /etc/letsencrypt/live/amt-control.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amt-control.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 200M;
    client_body_temp_path /tmp_big_files;
    client_body_timeout 120s;
    proxy_request_buffering off;


    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
       include  /etc/nginx/mime.types;
      proxy_pass http://app_amt_wiki_ver3;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_redirect off;
      access_log /var/log/nginx/access.log detailed;

      proxy_hide_header Content-Type;
      proxy_hide_header Content-Disposition;
    }

    location /wiki/static/ {
      alias /app/static/;
      add_header Cache-Control "public, immutable";
  }

    location ~ ^/wiki/files/([^/]+)$ {
      proxy_pass http://app_amt_wiki_ver3;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_redirect off;
      proxy_pass_request_headers on;
      proxy_hide_header X-Accel-Redirect;

      expires 1d;
  }
  location ~ ^/internal_files/([^/]+)$ {
    set $rule_matched "files internal";
    internal;

    include  /etc/nginx/mime.types;
    access_log /var/log/nginx/access.log detailed;
    root /app/media;
    try_files /$1 =404;

    # Поддержка стриминга (важно для видео)
    expires 1d;
    add_header Cache-Control "private";
  }


    location /static/ {
    alias /app/static/;
    add_header Cache-Control "public, immutable";
    }

  location /admin/static/ {
    alias /app/admin/static/;
    add_header Cache-Control "public, immutable";
    }

  location /favicon.ico {
    alias /app/static/favicon.ico;
    add_header Cache-Control "public, immutable";
  }


   # === БЛОКИРУЮЩИЕ LOCATION (в конце) ===

    # 4. Защита скрытых файлов
  location ~ /\. {
      set $rule_matched "safe";
      deny all;
      access_log off;
      log_not_found off;
      return 404;
  }

  # 5. Защита по расширениям
  location ~* \.(env|ini|conf|sql|bak|log|sh|key)$ {
      set $rule_matched "safe";
      deny all;
      access_log off;
      log_not_found off;
      return 404;
  }

    # 6. Защита директорий
  location ~ /(\.git|vendor|node_modules|logs) {
      set $rule_matched "safe";
      deny all;
      access_log off;
      log_not_found off;
      return 404;
  }

}