upstream app_amt_wiki_ver3 {
  server amt_wiki_ver3:5006;
  }

server {
  listen 80;
  server_name _;
  access_log debug;
  include  /etc/nginx/mime.types;
  client_max_body_size 1000M;
  client_body_in_file_only clean;
  client_body_temp_path /tmp_big_files;
  client_body_timeout 120s;

  proxy_request_buffering off;
#     proxy_http_version 1.1;      -- required to disable request buffering also for clients that send chunked encoding
#     client_max_body_size 0; 

    location / {
        proxy_pass http://app_amt_wiki_ver3;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
      alias /static/;
      }

    location admin/static/ {
      rewrite ^/admin/static/(.*)$ /static/$1 last;
      }


}



